// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const { assert } = require("chai");
const chai = require ('chai');
const expect = chai.expect;
const chrome = require ('selenium-webdriver/chrome');


describe('L6', function() {
  
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('L6', async function() {
    setTimeout(async function() {
    await driver.get("https://test.exevirtual.com/lucky6/index.php?deviceType=desktop&userUuid=AutomaticTest&sessionUuid=1e35114f-f081-4e6e-bd89-fb30b334f88b&language=sr&clientName=c2629cff41143af94bcec66d52117d75c370fb22&ccy=din")
    await driver.manage().window().setRect({ width: 1541, height: 819 })
    await driver.switchTo().frame(0)
    await driver.findElement(By.id("qup")).click()
    await driver.findElement(By.css(".randomOpen > .randMore:nth-child(1) > span")).click()
    await driver.findElement(By.id("addBet")).click()
    // {
      const element = await driver.findElement(By.id("addBet"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    // }
    // {
      const element2 = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element2, 0, 0).perform()
    // }
    await driver.findElement(By.css(".uplatiBtn")).click();
    await driver.findElement(By.id("deleteFromTicketBtn")).click()
  },20000);
  await driver.sleep(25000);
})
})
